# IMPORTANT!, THIS STEP REQUIRES THAT WE HAVE SAVED THE LATEST VERSION AND PUBLIS SCRIPT INTO new_publish_version.txt AS ENVIRONMENT VARIALBES
#
# CD INTO SOURCE CODE DIRECTORY
 

# READ IN THE VARIALBES IN THE TEXT FILE 
source ./npm_publish_version.txt

cd $PACKAGE_PATH

# INSTALL ALL REQ PACKAGES
echo "INSTALL NPM PACKAGES"
npm install

# UPDATE LOCAL PACKAGE.JSON WITH NEW VERSION
echo "PUBLISH_VERSION: " $PUBLISH_VERSION

npm version $PUBLISH_VERSION --no-git-tag-version

# BUILD THE PACKAGE WITH UPDATED PACKAGE.JSON SO THAT NPM REGISTRY GETS THE CORRECT VERSION
echo "BUILD PACKAGE"

npm run compBuild:test


# PUBLISH NEW VERSION TO NPM REPO USING INJECTED VARIABLE
echo "PUBLISH_SCRIPT: " $PUBLISH_SCRIPT

eval $PUBLISH_SCRIPT